#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate typed KOp dispatch thunks for the WebAssembly build.

The original engine dispatches operators with a hand written x86 trampoline
(kdoc.cpp, CallCode): it pushes N dwords onto the stack and does an indirect
`call`, which works because every operand -- sInt, sF32, pointer, and the small
POD aggregates -- is exactly one 32 bit stack slot under __stdcall.

WebAssembly has no such thing: call_indirect is statically typed, floats live
in f32 params rather than in reinterpreted i32 slots, and structs are passed
by reference.  So instead we generate one wrapper per operator that unpacks the
dword array into properly typed arguments and calls the handler directly.

Input : player_kkrieger/kkrieger_oplist.cpp  (the operator id -> handler table)
        *.hpp                                (the handler prototypes)
Output: wasm/kop_thunks.hpp                  (wrapper declarations)
        wasm/kop_thunks.cpp                  (wrappers + the KHandlers table)

Run from werkkzeug3_kkrieger/ :  python3 wasm/gen_thunks.py
"""

import re, glob, sys, os

MAX_VARARG = 32          # generated cases for the "..." operators

# type name -> number of 32 bit slots it occupies on the x86 stack
AGGREGATES = {
    'sInt2': 2, 'sInt3': 3, 'sInt4': 4,
    'sF322': 2, 'sF323': 3, 'sF324': 4,
    'sFSRT': 9,
}
INTLIKE = {'sInt', 'sU32', 'sS32', 'sBool', 'sU8', 'sU16', 'sChar'}


def parse_params(argstr):
    """Split a parameter list on top level commas and strip names/defaults."""
    argstr = argstr.strip()
    if argstr in ('', 'void'):
        return []
    parts, depth, cur = [], 0, ''
    for ch in argstr:
        if ch in '<(': depth += 1
        elif ch in '>)': depth -= 1
        if ch == ',' and depth == 0:
            parts.append(cur); cur = ''
        else:
            cur += ch
    parts.append(cur)

    out = []
    for raw in parts:
        p = raw.strip()
        if p == '...':
            out.append(('...', None))
            continue
        p = p.split('=')[0].strip()             # drop default arguments
        m = re.match(r'^(.*?)\s*([A-Za-z_]\w*)?$', p)
        ty = (m.group(1) if m else p).strip()
        if not ty:                               # unnamed parameter: "KOp *"
            ty = p.strip()
        ty = ty.replace('const ', '').strip()
        out.append((ty, None))
    return out


def emit_call_args(params, base=0):
    """Return (prologue lines, argument expressions, slots consumed)."""
    pro, args, i = [], [], base
    for n, (ty, _) in enumerate(params):
        if ty == '...':
            break
        if ty.endswith('*'):
            base_ty = ty[:-1].strip()
            args.append('(%s *)(sDInt)p[%d]' % (base_ty, i))
            i += 1
        elif ty in AGGREGATES:
            k = AGGREGATES[ty]
            pro.append('  %s a%d; __builtin_memcpy(&a%d, p + %d, %d);' % (ty, n, n, i, 4 * k))
            args.append('a%d' % n)
            i += k
        elif ty == 'sF32':
            pro.append('  sF32 a%d; __builtin_memcpy(&a%d, p + %d, 4);' % (n, n, i))
            args.append('a%d' % n)
            i += 1
        elif ty in INTLIKE:
            args.append('(%s)p[%d]' % (ty, i))
            i += 1
        else:
            raise SystemExit('unhandled parameter type %r' % ty)
    return pro, args, i


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    os.chdir(root)

    oplist = open('player_kkrieger/kkrieger_oplist.cpp', encoding='latin-1').read()
    entries = re.findall(
        r'^\s*(0x[0-9a-fA-F]+)\s*,\s*([A-Za-z_]\w*)\s*,\s*([A-Za-z_]\w*)\s*,',
        oplist, re.M)
    names = sorted({n for _, a, b in entries for n in (a, b)})

    protos = {}
    for h in sorted(glob.glob('*.hpp') + glob.glob('materials/*.hpp')):
        text = open(h, encoding='latin-1').read().replace('\r', '')
        for m in re.finditer(
                r'([A-Za-z_][\w:*\s]*?)\b(?:__stdcall|_stdcall)\s+([A-Za-z_]\w*)\s*\(([^;]*?)\)\s*;',
                text, re.S):
            nm = m.group(2)
            if nm in names and nm not in protos:
                protos[nm] = (m.group(1).strip(), ' '.join(m.group(3).split()))

    missing = [n for n in names if n not in protos]
    if missing:
        raise SystemExit('no prototype for: %s' % ', '.join(missing))

    hdr = ['// GENERATED by wasm/gen_thunks.py -- do not edit.',
           '#ifndef __KOP_THUNKS_HPP__',
           '#define __KOP_THUNKS_HPP__',
           '#include "kdoc.hpp"',
           '']
    src = ['// GENERATED by wasm/gen_thunks.py -- do not edit.',
           '//',
           '// One wrapper per operator handler: unpacks the dword parameter block that',
           '// KOp::Exec builds into properly typed arguments. Replaces the x86 CallCode',
           '// trampoline, which WebAssembly cannot express.',
           '',
           '#include "kdoc.hpp"',
           '#include "genbitmap.hpp"',
           '#include "genmaterial.hpp"',
           '#include "genmesh.hpp"',
           '#include "genminmesh.hpp"',
           '#include "genoverlay.hpp"',
           '#include "genscene.hpp"',
           '#include "geneffect.hpp"',
           '#include "genblobspline.hpp"',
           '#include "kkriegergame.hpp"',
           '#include "wasm/kop_thunks.hpp"',
           '']

    for nm in names:
        ret, argstr = protos[nm]
        params = parse_params(argstr)
        variadic = any(t == '...' for t, _ in params)
        fixed = [p for p in params if p[0] != '...']

        hdr.append('KObject *kopw_%s(sInt *p,sInt n);' % nm)
        src.append('KObject *kopw_%s(sInt *p,sInt n)' % nm)
        src.append('{')
        src.append('  (void)p; (void)n;')

        pro, args, used = emit_call_args(fixed)
        src.extend(pro)

        is_void = (ret.replace('class', '').strip() == 'void')

        if not variadic:
            call = '%s(%s)' % (nm, ','.join(args))
            if is_void:
                src.append('  %s;' % call)
                src.append('  return 0;')
            else:
                src.append('  return (KObject *)%s;' % call)
        else:
            # trailing arguments all have the type of the last named parameter
            last_ty = fixed[-1][0]
            assert last_ty.endswith('*'), last_ty
            base_ty = last_ty[:-1].strip()
            src.append('  const sInt nv = n - %d;' % used)
            src.append('  switch(nv<0?0:(nv>%d?%d:nv))' % (MAX_VARARG, MAX_VARARG))
            src.append('  {')
            for k in range(MAX_VARARG + 1):
                extra = ['(%s *)(sDInt)p[%d]' % (base_ty, used + j) for j in range(k)]
                call = '%s(%s)' % (nm, ','.join(args + extra))
                if is_void:
                    src.append('  case %d: %s; return 0;' % (k, call))
                else:
                    src.append('  case %d: return (KObject *)%s;' % (k, call))
            src.append('  }')
            src.append('  return 0;')

        src.append('}')
        src.append('')

    src.append('/****************************************************************************/')
    src.append('')
    src.append('KHandler KHandlers[] =')
    src.append('{')
    for oid, init, exec_ in entries:
        src.append('  %s, kopw_%s, kopw_%s,' % (oid, init, exec_))
    src.append('  0,0,0,')
    src.append('};')
    src.append('')

    hdr.append('')
    hdr.append('#endif')

    open('wasm/kop_thunks.hpp', 'w').write('\n'.join(hdr) + '\n')
    open('wasm/kop_thunks.cpp', 'w').write('\n'.join(src) + '\n')
    print('generated %d wrappers, %d table entries' % (len(names), len(entries)))


if __name__ == '__main__':
    main()
