/* Normally generated by MojoShader's CMake build; hand-written for the
 * .kkrieger wasm port (vendored from github.com/icculus/mojoshader). */
#define MOJOSHADER_VERSION 1
#define MOJOSHADER_CHANGESET "kkrieger-wasm-vendored"
